### ISSUE TITLE
Doesn't work with Caliburn.Micro v1.3.1

### ISSUE THREAD

**Issue by DavidBurela** [vcaraulean/Caliburn.Micro.Telerik#10]
The latest version of Caliburn has changed the method signature of
IWindowManager.ShowNotification

Also the ConventionManager.SetBinding signature has changed. Meaning that TelerikConventions.Install no longer compiles either.

**Comment by vcaraulean** [comment]
Should be OK now. Let me know if you have any issues...

**Comment by DavidBurela** [comment]
That was really quick. I appreciate it.
