### ISSUE TITLE
RadTab view model IsEnabled property binding dont work?

### ISSUE THREAD

**Issue by nihique** [vcaraulean/Caliburn.Micro.Telerik#12]
Hi,

I have view that dynamically loads telerik Tabs view models:

[telerik:RadTabControl x:Name="Items" Grid.Row="1" Margin="10,0,0,0" /]

I have set IsEnabled property onone of the Tabs view models to false, but that Tab is always enabled.

Is this supported? If not, how can I add it?

Thx,

M.

**Comment by vcaraulean** [comment]
I've tried to plug it with a convention but cannot make it work.

As a workaround you may use solution suggested on SO or either this code:

```
<telerik:RadTabControl.ItemContainerStyle>
    <Style TargetType="telerik:RadTabItem">
        <Setter Property="IsEnabled" Value="{Binding IsEnabled}" />
    </Style>
</telerik:RadTabControl.ItemContainerStyle>
```

This will be the most reliable way to achieve it...

**Comment by nihique** [comment]
Thanks that works. I have also tried ConventionManager, but was not successful...
