### ISSUE TITLE
Examples seem to be missing the theme. 

### ISSUE THREAD

**Issue by terencecraig** [vcaraulean/Caliburn.Micro.Telerik#13]
Hi 

Thanks for the project very useful.  A couple of minor issues. When I first downloaded the projects.  I had to clean up some of the references that had specific version attached because I had a later version of Telerik for example:  

``` xml
 <Reference Include="Telerik.Windows.Controls, Version=2012.2.607.1050, Culture=neutral, PublicKeyToken=5803cfa389c90ce7, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\..\..\..\Program Files (x86)\Telerik\RadControls for Silverlight Q3 2012\Binaries\Silverlight\Telerik.Windows.Controls.dll</HintPath>
    </Reference>
```

. Maybe it is just my environment but the specific version = false seems to only work sporadically for me. It might be a good idea to just strip the version info from all of the Telerik references since they release so often. 

``` xml
<Reference Include="Telerik.Windows.Controls"/>
```

I also had to add a reference to the Windows 8 theme since it wasn't included in the build. 

``` xml
 <Reference Include="Telerik.Windows.Themes.Windows8"/>
```

This did not cause a compile error but did result in a runtime error for both example projects in appbootstrapper.
Thanks again for sharing your work.

**Comment by vcaraulean** [comment]
Thanks for missing W8 theme references, fixed now...

As for references to Telerik's assemblies without a strong name - does it work for you? Have you tried it in both SL & WPF targets? Do you know if this can be automated (6 projects to adjust by hand isn't particularly funny)?

& Thanks for heads up!
