### ISSUE TITLE
Add support for RadDiagram

### ISSUE THREAD

**Issue by tibel** [vcaraulean/Caliburn.Micro.Telerik#14]
See https://caliburnmicro.codeplex.com/discussions/438814 for details.

**Comment by vcaraulean** [comment]
I had no chance yet to use RadDiagrams. 
If somebody wants to provide the code I’ll be happy to integrate it (or accept a pull request).

From: Thomas Ibel 
Sent: Friday, April 5, 2013 6:55 PM
To: vcaraulean/Caliburn.Micro.Telerik 
Subject: [Caliburn.Micro.Telerik] Add support for RadDiagram (#14)

See https://caliburnmicro.codeplex.com/discussions/438814 for details.
