### ISSUE TITLE
Windows Phone support

### ISSUE THREAD

**Issue by igorkulman** [vcaraulean/Caliburn.Micro.Telerik#18]
Any plans for a Windows Phone version?

**Comment by vcaraulean** [comment]
Not the near future. I'm not anymore involved in any projects that are using Telerik's controls. Unless I'd get in my hands a license for Telerik's Windows Phone controls to use in my own WP apps it will probably not happen. 

If anyone wants to step in and contribute a WP specific version of CM conventions - I'll be happy to accept pull requests.
